"""update

Revision ID: 64019a97afa5
Revises: 58330e0fa111
Create Date: 2026-05-23 20:59:49.518368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64019a97afa5'
down_revision: Union[str, Sequence[str], None] = '58330e0fa111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
