"""update

Revision ID: d3f0dc83f9e9
Revises: 27bf364dee16
Create Date: 2026-05-23 20:24:07.803476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f0dc83f9e9'
down_revision: Union[str, Sequence[str], None]  = 'e7af78f2a43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Safely add the column as Nullable first
    op.add_column(
        'events',
        sa.Column('date_event', sa.DateTime(), nullable=True)
    )

    # 2. Populate old data rows with a current fallback timestamp
    op.execute("UPDATE events SET date_event = NOW() WHERE date_event IS NULL")

    # 3. Enforce the NOT NULL rule cleanly
    op.alter_column(
        'events',
        'date_event',
        existing_type=sa.DateTime(),
        nullable=False
    ) ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date_event')
    # ### end Alembic commands ###
