"""create events table

Revision ID: e7af78f2a43f
Revises: 
Create Date: 2026-05-23 00:34:50.342123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7af78f2a43f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('location', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
