"""update

Revision ID: f25c2713a521
Revises: bfc7cda0e2b1
Create Date: 2026-05-24 17:48:23.779135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25c2713a521'
down_revision: Union[str, Sequence[str], None] = 'bfc7cda0e2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participants', 'joined')
    # ### end Alembic commands ###
